### ISSUE TITLE
Poetry run not working

### ISSUE THREAD

**Issue by xeb** [xeb/dalle-mini-tools#4]
Running into this issue:
```
$ poetry run python generate.py "Does this work?"
Traceback (most recent call last):
  File "/media/xeb/.../projects/dalle-mini-tools/generate.py", line 8, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
```

$ poetry run python request.py "Some way of using data to make decisions"
Traceback (most recent call last):
  File "/media/xeb/.../projects/dalle-mini-tools/request.py", line 5, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'

But using `poetry shell` *does* work:
```
$ poetry shell
Virtual environment already activated: /home/xeb/.cache/pypoetry/virtualenvs/dalle-mini-tools-4Bbrb4Fl-py3.10
```
Then:
```
$ python request.py "service to service level dependency"
Using run_name='run_20220624-144835_service-to-service-level'
Received response={'MD5OfMessageBody': 'e92094124...', 'RetryAttempts': 0}}
run_20220624-144835_service-to-service-level
```

**Comment by warmlogic** [comment]
As mentioned on slack, I believe you need to update the lock file and your environment first with [poetry update](https://python-poetry.org/docs/cli#update)

I think this would be the same thing as pip installing a requirements file

**Comment by xeb** [comment]
Tried that to no avail. I'm going to do a clean checkout on a fresh linux VM (no GPU passthrough) to double check.
